"""add tasks table

Revision ID: a3c5b35665c7
Revises: 524e96cbdb59
Create Date: 2026-07-18 10:05:44.180105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'a3c5b35665c7'
down_revision: Union[str, Sequence[str], None] = '524e96cbdb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # tasks 表在早期开发阶段由 create_database_tables()
    # （SQLAlchemy 的 Base.metadata.create_all）先行创建，
    # 结构与本迁移完全一致。这里先探测表是否已存在，
    # 已存在则跳过建表，避免破坏或清空现有任务数据；
    # 在全新数据库上运行时会按正常流程创建表和索引。
    bind = op.get_bind()
    inspector = inspect(bind)

    if 'tasks' in inspector.get_table_names():
        return

    op.create_table(
        'tasks',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('task_type', sa.String(length=64), nullable=False),
        sa.Column('assigned_agent', sa.String(length=100), nullable=True),
        sa.Column('priority', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('payload', sa.JSON(), nullable=False),
        sa.Column('result', sa.JSON(), nullable=True),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_agent'), 'tasks', ['assigned_agent'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_agent'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
